//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMDienThoai
    {
        public string MaDienThoai { get; set; }
        public string TenDienThoai { get; set; }
        public string MaHangSX { get; set; }
        public string MaNuocSX { get; set; }
        public string ThoiGianBaoHanh { get; set; }
        public string Anh { get; set; }
        public string MaRam { get; set; }
        public string MaRom { get; set; }
        public string MaHeDieuHanh { get; set; }
        public Nullable<int> DonGiaBan { get; set; }
        public string MaGiaTien { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual HeDieuHanh HeDieuHanh { get; set; }
        public virtual Ramm Ramm { get; set; }
        public virtual Rom Rom { get; set; }
        public virtual Tien Tien { get; set; }
        public virtual HangSanXuat HangSanXuat { get; set; }
        public virtual NuocSanXuat NuocSanXuat { get; set; }
        public virtual ThongSoDienThoai ThongSoDienThoai { get; set; }
    }
}
